name: Assign Copilot Reviewer

on:
  pull_request:
    branches: [develop]
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Request review from GitHub Copilot
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['github-copilot']
            });
