name: Publish to GitHub Packages

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: false
      GPG_PASSPHRASE:
        required: false
  push:
    branches: [main]
    paths:
      - '**/pom.xml'
      - '.github/workflows/publish-github-packages.yml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
      - name: Import GPG key
        if: env.GPG_PRIVATE_KEY != ''
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish modules
        run: |
          if [ -n "$GPG_PRIVATE_KEY" ]; then
            ./mvnw -q -P release deploy -Dgpg.passphrase="$GPG_PASSPHRASE" \
              -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }}
          else
            ./mvnw -B -q deploy -DskipTests -Dgpg.skip=true \
              -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }}
          fi
